/** Curated ISO 3166-1 alpha-2 list for the nationality select (PoC scope). */
export const COUNTRIES: readonly { code: string; label: string }[] = [
  { code: "CH", label: "Switzerland" },
  { code: "DE", label: "Germany" },
  { code: "LI", label: "Liechtenstein" },
  { code: "AT", label: "Austria" },
  { code: "FR", label: "France" },
  { code: "IT", label: "Italy" },
  { code: "ES", label: "Spain" },
  { code: "PT", label: "Portugal" },
  { code: "GB", label: "United Kingdom" },
  { code: "IE", label: "Ireland" },
  { code: "NL", label: "Netherlands" },
  { code: "BE", label: "Belgium" },
  { code: "LU", label: "Luxembourg" },
  { code: "DK", label: "Denmark" },
  { code: "SE", label: "Sweden" },
  { code: "NO", label: "Norway" },
  { code: "FI", label: "Finland" },
  { code: "PL", label: "Poland" },
  { code: "CZ", label: "Czechia" },
  { code: "SK", label: "Slovakia" },
  { code: "HU", label: "Hungary" },
  { code: "SI", label: "Slovenia" },
  { code: "HR", label: "Croatia" },
  { code: "RO", label: "Romania" },
  { code: "BG", label: "Bulgaria" },
  { code: "GR", label: "Greece" },
  { code: "RS", label: "Serbia" },
  { code: "BA", label: "Bosnia and Herzegovina" },
  { code: "MK", label: "North Macedonia" },
  { code: "AL", label: "Albania" },
  { code: "TR", label: "Türkiye" },
  { code: "UA", label: "Ukraine" },
  { code: "US", label: "United States" },
  { code: "CA", label: "Canada" },
  { code: "BR", label: "Brazil" },
  { code: "IN", label: "India" },
  { code: "CN", label: "China" },
  { code: "JP", label: "Japan" },
  { code: "AU", label: "Australia" },
];
